@startuml
!include style.puml
show member
hide empty member
title "Initial State"

Object "<u>:CommandBox" as CommandBox
Object "<u>:CommandHistory" as CommandHistory {
    commandHistory = []
    current = 0
}


CommandBox -- CommandHistory

@enduml